# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: | 
       echo "开始进行release构建" 
       ./gradlew assembleRelease
       echo "release构建完毕" 
    - name: Upload Apk
      run: echo "上传apk至Artifacts" 
    - uses: actions/upload-artifact@v2
      with:
        name: BTHeadsetHelper
        path: app/build/outputs/apk/release/app-release.apk
